export const WORD_DEFINITIONS = new Map([
	['MANJA', 'Go MANJA your loved ones todeh!'],
	['KILAT', 'This Word-leh! game is excellent. So KILAT!'],
	['WHACK', 'Just play for fun lah, anyhow WHACK!'],
	['SUAKU', 'Who never heard of WORD-LEH? So SUAKU!'],
	['HAVOC', 'Last time very havoc. Nowadays stay home play WORD-LEH!'],
	['SHACK', 'Wah, so tired. Play WORD-LEH until SHACK!'],
	['TULAN', 'Cannot guess the answer, angry liao. Sibeh TULAN!'],
	['DONCH', 'DONCH worry. Tomolo can play again!'],
	['SIONG', 'Todeh game very hard. SIONG ah!'],
	['TERUK', 'Todeh game oso hard. TERUK!'],
	['BODOH', 'You not BODOH lah. You vsery clever!'],
	['CABUT', 'Still working? Mai tu liao! Faster CABUT go home play WORD-LEH!'],
	['HABIS', 'Guess 6 times oredi still dunno the WORD-LEH? HABIS lah!'],
	['HOSEH', 'How are you? HOSEH bo?'],
	['MAFAN', 'English grammar so mafan, just spiak Singlish easier!'],
	['SALAH', 'Cannot guess today\'s WORD-LEH, so SALAH!'],
	['JELAK', 'Ate too much pizza, so JELAK!'],
	['NGEOW', 'Dun be NGEOW about the spelling. Could be ngiao too! '],
	['TEKAN', 'Dun TEKAN me if WORD-LEH! got no more 5 letter words liao'],
	['AIYOH', 'Did you know AIYOH is in the OED?'],
	['BOTAK', 'Weather so hot, I want to shave BOTAK.'],
	['ROJAK', 'Singlish is like ROJAK, everything anyhow mix.'],
	['TAHAN', 'Buay TAHAN, cannot take it anymore!'],
])